# Generated by Django 4.0.3 on 2022-04-02 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenInfo',
            fields=[
                ('canteen_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active_or_not', models.BooleanField()),
                ('last_scan_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('profile_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userdetail.profile')),
            ],
        ),
    ]
