# Generated by Django 4.0.3 on 2022-04-03 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canteenInfo', '0003_alter_canteeninfo_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteeninfo',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 3, 9, 5, 50, 556539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='canteeninfo',
            name='last_scan_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 8, 35, 50, 556417, tzinfo=utc)),
        ),
    ]
