# Generated by Django 4.0.1 on 2022-04-03 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='latest_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 0, 16, 17, 293626, tzinfo=utc)),
        ),
    ]
