# Generated by Django 4.0.1 on 2022-04-03 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_latest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='latest_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 0, 48, 55, 358359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(max_length=500),
        ),
    ]
