# Generated by Django 4.0.3 on 2022-04-03 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_latest_date_alter_menu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='latest_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
